### ISSUE TITLE
About "exp/dual_cyclegan/checkpoint-600000steps.pkl"

### ISSUE THREAD

**Issue by LittleFlyingSheep** [chomeyama/DualCycleGAN#2]
Hi, I am interested in your work. Could you please share the "exp/dual_cyclegan/checkpoint-600000steps.pkl" file? This can help me to inference the resolution process without the cost of training.

**Comment by chomeyama** [comment]
Thank you for your interest!

However, this research was conducted on the company's computational servers during my internship, so I do not have the trained model. Therefore, I'm sorry but you would need to train the model yourself to actually test it. 

If you have any questions or uncertainties regarding the training process, please feel free to ask!

**Comment by LittleFlyingSheep** [comment]
收到
